language: c
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install
  -qq build-essential; fi
script: "./build.sh && mv -v releases/bash releases/bash-$TRAVIS_OS_NAME"
deploy:
  provider: releases
  api_key:
    secure: Q7Rj57lrX55L+bdbRg59TTuf7rroQeDjw5emXVG4JSHPMiZOYZE75LM8VZ9clvGUjdNxlcPcGIATNBA9e8i64hZGyZ3QRr3QqJ87gtFZfiMVHin02+WCQEa4BA24UtmygI0xZ99jCVJCw7NtbYEP/6miDbC5NqiShX2DP1Ygt9E=
  file: releases/bash-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    repo: robxu9/bash-static
    tags: true
    all_branches: true
