language: c
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install
  -qq build-essential; fi
script: "./build.sh && mv -v releases/bash releases/bash-$TRAVIS_OS_NAME"
deploy:
  provider: releases
  api_key:
    secure: Ddq9WgcyJu2z+zy+3sOhHMSm1DgZ0BsgzrKJ3xzSmB7uG5qmeyP2nUj7SU7Xj3gBv9tP1n5wovw0bZlLbW02FGRYTFPdBqX8vMvGU2Zfa4b5HeyntWSCWTTwDx7i2S0/BY+cSlVwjQ8krMEMI2V0yp9r27pTUXSJhI75ZqJfSu0=
  file: releases/bash-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    repo: robxu9/bash-static
    tags: true
    all_branches: true
