language: c
os:
- linux
- osx
before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install
  -qq build-essential; fi
script: "./build.sh && mv -v releases/bash releases/bash-$TRAVIS_OS_NAME"
deploy:
  provider: releases
  api_key:
    secure: UfRT4iSXWMjQLcTHje+WybtCM9WZJ4Ak/CzBDtlNSgAlLM3/+0x9u5IrKnKEdtwMX1ri+gMt08EI0Hdkc8gjAQr4Pi0HIyUhb9D4xFNJLxsQxKbkvC0nVVkSHZuS1dDE8V7323Oro5i7DF15Gx6EwWohwg3VrKhsUq91QbwmsCY=
  file: releases/bash-$TRAVIS_OS_NAME
  skip_cleanup: true
  on:
    repo: robxu9/bash-static
    tags: true
    all_branches: true
