name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: install apt packages
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq build-essential gpg
    - name: install msys2 packages
      if: ${{ matrix.os == 'windows-latest' }}
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          gnupg
    - name: install homebrew packages
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install gnupg
    - name: build
      run: ./build.sh && mv -v releases/bash releases/bash-${{matrix.os}}
      shell: bash
    - uses: actions/upload-artifact@v2  
      with:
        name: bash-${{matrix.os}}
        path: releases/bash-${{matrix.os}}
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: generate changelog
        run: ./changelog.sh
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: make executable
        run: chmod +x artifacts/*
      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*
          body_path: NOTES.txt
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
